package exception;

public class DemoTry {

	public static void main(String[] args) {
		NestedTryCatch.check();

	}

}
